# Generated by Django 2.1.7 on 2020-09-06 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookmarkManag', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerbookmark',
            options={'ordering': ('created_at',)},
        ),
        migrations.AlterField(
            model_name='customerbookmark',
            name='bookmark',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BookmarkManag.Bookmark'),
        ),
        migrations.AlterField(
            model_name='customerbookmark',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BookmarkManag.Customer'),
        ),
    ]
